name: Deploy

on:
  push:
    branches:
      - master # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_SERVER_ID: ${{secrets.SSH_SERVER_ID}}
          SSH_KNOWN_HOST: ${{secrets.SSH_KNOWN_HOST}}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          echo "$SSH_SERVER_ID"> id
          chmod 600 keyfile
          mkdir -p ~/.ssh
          echo "$SSH_KNOWN_HOST" > kh
          cp kh ~/.ssh/known_hosts
          ssh -T -i keyfile id "sudo bash ~/deploy.sh"
